http:
  host: '0.0.0.0'
  port: 8300

nmap:
  bin: nmap

suricata:
  bin: suricata
  config-file: /etc/suricata/suricata.yaml
  rules-path: /etc/suricata/rules
  push-rules-cron: '*/10 * * * * *'

elasticsearch:
  url: 'http://localhost:9200'
  sniff:
    interval: 120000

logstash:
  bin: /home/kurefm/Apps/logstash-2.4.1/bin/logstash
  config-file: suricata/logstash.conf

bismuth:
  # `all`(hs, ids, node), `agent`(hs, ids), `hs`, `ids`, `node`
  mode: all
  api:
    prefix: '/api/v1/'
  config:
    index: .bismuth
    type: config
    cron: '*/10 * * * * *'
  alive:
    index: .bismuth
    type: alive
    cron: '*/10 * * * * *'
  info:
    index: .bismuth
    type: info
    cron: '*/10 * * * * *'


winston:
  logger:
    console:
      level: debug
      colorize: all
    dailyRotateFile:
      level: debug
      filename: ./log/bismuth
      datePattern: .yyyy-MM-dd.log
      maxsize: 10000000
      maxFiles: 30
      zippedArchive: true
  labels:
    - Node
    - Elasticsearch
    - Base
    - Nmap
    - Suricata
    - Logstash
